apiVersion: v1
kind: Secret
metadata:
  name: github-deployer-token
  namespace: learningsteps
  annotations:
    kubernetes.io/service-account.name: github-deployer
  labels:
    app: learningsteps-api
    component: ci-cd
type: kubernetes.io/service-account-token
